# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/22253/Desktop/huibian/project_single2/project_single2.cache/wt [current_project]
set_property parent.project_path C:/Users/22253/Desktop/huibian/project_single2/project_single2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/22253/Desktop/huibian/project_single2/project_single2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/ALU.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/ALUControl.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/new/BCD7.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/Control.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/DataMemory.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/new/Debounce.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/InstructionMemory2.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/RegisterFile.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/new/clk_gen.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/new/count8.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/new/multichoice.v
  C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/sources_1/imports/single-cycle/MipsCPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/constrs_1/new/1.xdc
set_property used_in_implementation false [get_files C:/Users/22253/Desktop/huibian/project_single2/project_single2.srcs/constrs_1/new/1.xdc]


synth_design -top CPU -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
